name: Dan Cristo
favicon: null
layout_spectrum: 0.29898
typography_spectrum: 0.50821
title: Music by Dan Cristo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4dd5e9'
    - '#3e7cab'
    - '#2d2a2b'
    - '#a38d99'
    - '#ddefff'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
