name: Dan Cristo
favicon: null
layout_spectrum: 0.5957674607634544
typography_spectrum: 0.6812248334754258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4411202485207468
  lightness: 0.5149067642632872
  saturation: 0.6345417180564255
  rhythmicContrast: 0.8391372004989535
purpose: []
