name: Dan Cristo
favicon: null
layout_spectrum: 0.29898
typography_spectrum: 0.74534
title: Music by Dan Cristo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#806069'
    - '#593e42'
    - '#c2366c'
    - '#24171a'
    - '#c28eab'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
